"""Module 02 — Write Problems: pytest.

Fails against the shipped naive `guarded_write` body; passes once you add a
guard. Do not edit this file.
"""
import importlib.util
from pathlib import Path
from typing import Generator

from nova.models import Obligation
from nova.scheduler import Scheduler
from nova.store import RecordStore

# Loaded by absolute path (not `import your_fix`) so this module name doesn't
# collide with modules/03_state/your_fix.py in pytest's module cache.
_spec = importlib.util.spec_from_file_location("write_path_your_fix", Path(__file__).parent / "your_fix.py")
_your_fix = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_your_fix)
guarded_write = _your_fix.guarded_write

CONFLICT_SCRIPT = ["A:read", "B:read", "A:write", "B:write"]


def write_run(store: RecordStore, ob: Obligation) -> Generator[str, None, None]:
    store.get_obligations(ob.client_id)
    yield "read"
    guarded_write(store, ob)
    yield "write"


def test_conflict_produces_no_duplicate(tmp_path):
    store = RecordStore(tmp_path / "write_test.db")
    store.init_schema()
    ob = Obligation(
        client_id="alpha",
        text="File Form ADV by March 31",
        source_doc="alpha_doc_1.md",
        idempotency_key="alpha-adv-2025",
    )

    Scheduler(CONFLICT_SCRIPT).run(
        lambda: write_run(store, ob),
        lambda: write_run(store, ob),
    )

    obligations = store.get_obligations("alpha")
    assert len(obligations) == 1, f"expected exactly one obligation, got {len(obligations)}"
    assert obligations[0].text == ob.text
    assert obligations[0].idempotency_key == ob.idempotency_key
