"""Module 02 — Write Problems: pytest. Do not edit this file.

Two tests, on purpose:

  test_replayed_retry...   — a retry that replays the SAME memo. Guarding the
      effect fixes this, whatever you key on.

  test_regenerated_retry...— a retry where the agent re-ran and the model
      REWROTE the memo. Keying on the memo (the output) now double-charges;
      only keying on the fee's intent survives.

A fix that passes the first and fails the second is the lesson, not a bug.
"""
import importlib.util
from pathlib import Path

from nova.agent import load_document, payment_memo_prompt
from nova.effects import PaymentGateway
from nova.frozen_llm import FrozenLLM
from nova.store import RecordStore

# Load your_fix by absolute path so this module name doesn't collide with
# modules/03_state/your_fix.py in pytest's module cache.
_spec = importlib.util.spec_from_file_location("write_path_your_fix", Path(__file__).parent / "your_fix.py")
_your_fix = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_your_fix)
charge_client_fee = _your_fix.charge_client_fee

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "fixtures"
CLIENT_ID = "alpha"
PERIOD = "Q1-2026"
AMOUNT = 2500
SOURCE_DOC = "billing_instruction.md"


def _memo(llm: FrozenLLM, attempt: int) -> str:
    doc = load_document(CLIENT_ID, SOURCE_DOC)
    return llm.complete(payment_memo_prompt(CLIENT_ID, PERIOD, doc, attempt))


def _fresh():
    llm = FrozenLLM(FIXTURES / "llm_responses")
    return llm, PaymentGateway()


def test_two_runs_really_produce_different_memos():
    """Sanity: the second failure is only meaningful if the agent's output varies."""
    llm = FrozenLLM(FIXTURES / "llm_responses")
    assert _memo(llm, 1) != _memo(llm, 2)


def test_replayed_retry_charges_the_client_only_once(tmp_path):
    """The easy retry: the SAME memo is replayed. Guarding the effect fixes it."""
    llm, gateway = _fresh()
    store = RecordStore(tmp_path / "replayed.db")
    store.init_schema()

    memo = _memo(llm, 1)
    for _ in range(2):  # the call is retried with the same request
        charge_client_fee(gateway, store, CLIENT_ID, PERIOD, AMOUNT, memo)

    charged = gateway.charges_for(CLIENT_ID)
    assert len(charged) == 1, (
        f"a replayed retry charged the client {len(charged)} times -- guard the "
        f"effect before it happens, don't just dedup the database row"
    )


def test_regenerated_retry_charges_the_client_only_once(tmp_path):
    """The real retry: the agent re-ran and the model REWROTE the memo.

    Same fee, same client, same period -- but a different memo. Keying on the
    memo gives the two attempts different keys and double-charges the card.
    """
    llm, gateway = _fresh()
    store = RecordStore(tmp_path / "regenerated.db")
    store.init_schema()

    for attempt in (1, 2):  # the agent re-runs; the model rewrites the memo
        memo = _memo(llm, attempt)
        charge_client_fee(gateway, store, CLIENT_ID, PERIOD, AMOUNT, memo)

    charged = gateway.charges_for(CLIENT_ID)
    assert len(charged) == 1, (
        f"a regenerated retry charged the client {len(charged)} times -- key the "
        f"charge on the fee's intent (client + period), not on the agent's memo"
    )
