"""Module 02 — Write Problems: pytest.

Fails against the shipped naive `obligation_identity` (keyed on the model's
variable text); passes once you key on stable intent. Do not edit this file.
"""
import importlib.util
from pathlib import Path

from nova.agent import extraction_prompt, load_document
from nova.effects import RegulatoryFilingSystem
from nova.frozen_llm import FrozenLLM
from nova.store import RecordStore

# Load your_fix by absolute path so this module name doesn't collide with
# modules/03_state/your_fix.py in pytest's module cache.
_spec = importlib.util.spec_from_file_location("write_path_your_fix", Path(__file__).parent / "your_fix.py")
_your_fix = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_your_fix)
obligation_identity = _your_fix.obligation_identity

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "fixtures"
CLIENT_ID = "alpha"
SOURCE_DOC = "engagement_letter.md"


def _extract(llm: FrozenLLM, attempt: int) -> str:
    document = load_document(CLIENT_ID, SOURCE_DOC)
    return llm.complete(extraction_prompt(CLIENT_ID, SOURCE_DOC, document, attempt))


def test_two_runs_really_produce_different_text():
    """Sanity: the failure is only meaningful if the outputs actually diverge."""
    llm = FrozenLLM(FIXTURES / "llm_responses")
    assert _extract(llm, 1) != _extract(llm, 2)


def test_retry_files_obligation_only_once(tmp_path):
    llm = FrozenLLM(FIXTURES / "llm_responses")
    store = RecordStore(tmp_path / "write_test.db")
    store.init_schema()
    filing = RegulatoryFilingSystem(store)

    for attempt in (1, 2):
        text = _extract(llm, attempt)
        key = obligation_identity(CLIENT_ID, SOURCE_DOC, text)
        filing.submit(key, CLIENT_ID, text)

    filed = filing.filings()
    assert len(filed) == 1, (
        f"expected exactly one filing to reach the regulator, got {len(filed)} "
        "-- identity must be derived from stable intent, not the variable text"
    )
