"""Module 03 — State, Memory & Recovery: pytest.

Fails against the shipped naive `your_fix.py`; passes once you fix both
tasks. Do not edit this file.
"""
import importlib.util
from pathlib import Path

from nova.agent import Agent
from nova.frozen_llm import FrozenLLM
from nova.scheduler import Scheduler
from nova.store import RecordStore
from nova.trace import Tracer

# Loaded by absolute path (not `import your_fix`) so this module name doesn't
# collide with modules/02_write_path/your_fix.py in pytest's module cache.
_spec = importlib.util.spec_from_file_location("state_your_fix", Path(__file__).parent / "your_fix.py")
_your_fix = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_your_fix)
IsolatedState = _your_fix.IsolatedState
run_recoverable = _your_fix.run_recoverable

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "fixtures"

CONTAMINATION_SCRIPT = [
    "A:read", "A:reason", "B:read", "B:reason", "A:write", "A:draft", "B:write", "B:draft",
]


def _build_agent(store: RecordStore, tracer: Tracer, state) -> Agent:
    llm = FrozenLLM(FIXTURES / "llm_responses")
    return Agent(store, llm, FIXTURES / "embeddings", tracer, state)


def test_isolation_alpha_briefing_has_no_beta_data(tmp_path):
    store = RecordStore(tmp_path / "state_isolation.db")
    store.init_schema()
    tracer = Tracer(tmp_path / "isolation_trace.jsonl")

    shared_state = IsolatedState()
    agent_alpha = _build_agent(store, tracer, shared_state)
    agent_beta = _build_agent(store, tracer, shared_state)

    Scheduler(CONTAMINATION_SCRIPT).run(
        lambda: agent_alpha.run_steps("alpha", "run-a"),
        lambda: agent_beta.run_steps("beta", "run-b"),
    )

    alpha_briefing = store.get_briefing("alpha")
    assert "beta" not in alpha_briefing["content"].lower()
    assert "alpha" in alpha_briefing["content"].lower()


def test_recovery_no_duplicate_after_kill(tmp_path):
    store = RecordStore(tmp_path / "state_recovery.db")
    store.init_schema()
    tracer = Tracer(tmp_path / "recovery_trace.jsonl")
    state = IsolatedState()
    agent = _build_agent(store, tracer, state)

    result = run_recoverable(agent, "alpha", "run-recover", kill_after="write")
    assert result is None  # simulated crash

    resumed = run_recoverable(agent, "alpha", "run-recover")
    assert resumed is not None
    assert resumed.client_id == "alpha"

    obligations = store.get_obligations("alpha")
    assert len(obligations) == 1, f"expected exactly one obligation after recovery, got {len(obligations)}"
