"""Module 03 — State, Memory & Recovery: pytest.

Fails against the shipped naive `IsolatedState` (shared memory leaks across
tenants); passes once you namespace memory by run_id. Do not edit this file.
"""
import importlib.util
from pathlib import Path

from nova.agent import Agent
from nova.frozen_llm import FrozenLLM
from nova.scheduler import Scheduler
from nova.store import RecordStore
from nova.trace import Tracer

# Load your_fix by absolute path so this module name doesn't collide with
# modules/02_write_path/your_fix.py in pytest's module cache.
_spec = importlib.util.spec_from_file_location("state_your_fix", Path(__file__).parent / "your_fix.py")
_your_fix = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_your_fix)
IsolatedState = _your_fix.IsolatedState

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "fixtures"

CONTAMINATION_SCRIPT = ["A:read", "A:reason", "B:read", "B:reason", "A:save", "B:save"]


def _build_agent(store: RecordStore, tracer: Tracer, memory) -> Agent:
    llm = FrozenLLM(FIXTURES / "llm_responses")
    return Agent(store, llm, FIXTURES / "embeddings", tracer, memory)


def test_isolation_alpha_summary_has_no_beta_data(tmp_path):
    store = RecordStore(tmp_path / "state_isolation.db")
    store.init_schema()
    tracer = Tracer(tmp_path / "isolation_trace.jsonl")

    memory = IsolatedState()
    agent_alpha = _build_agent(store, tracer, memory)
    agent_beta = _build_agent(store, tracer, memory)

    Scheduler(CONTAMINATION_SCRIPT).run(
        lambda: agent_alpha.run_steps("alpha", "run-a"),
        lambda: agent_beta.run_steps("beta", "run-b"),
    )

    alpha_summary = store.get_summary("alpha")
    assert "beta" not in alpha_summary["content"].lower()
    assert "alpha" in alpha_summary["content"].lower()
