"""Module 03 — State, Memory & Recovery: pytest. Do not edit this file.

Two tests, on purpose:

  test_isolation... — two tenants run at once. The naive shared key leaks Beta
      into Alpha's summary. Keying memory by run_id OR by tenant both fix this.

  test_recovery... — a run crashes after reasoning, another tenant reuses the
      same run/attempt id, then the first run resumes from its checkpoint. Keying
      by run_id now loads the WRONG tenant's memory; only keying by the unit of
      work (the tenant) survives.

A fix that passes the first test and fails the second is the lesson, not a bug.
"""
import importlib.util
from pathlib import Path

from nova.agent import Agent, MemoryStore
from nova.frozen_llm import FrozenLLM
from nova.scheduler import Scheduler
from nova.store import RecordStore
from nova.trace import Tracer

# Load your_fix by absolute path so this module name doesn't collide with
# modules/02_write_path/your_fix.py in pytest's module cache.
_spec = importlib.util.spec_from_file_location("state_your_fix", Path(__file__).parent / "your_fix.py")
_your_fix = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_your_fix)
state_key = _your_fix.state_key

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "fixtures"

CONTAMINATION_SCRIPT = ["A:read", "A:reason", "B:read", "B:reason", "A:save", "B:save"]


def _build_agent(store: RecordStore, tracer: Tracer, memory: MemoryStore) -> Agent:
    llm = FrozenLLM(FIXTURES / "llm_responses")
    return Agent(store, llm, tracer, memory, state_key)


def test_isolation_alpha_summary_has_no_beta_data(tmp_path):
    """Live: Alpha and Beta interleave through one shared MemoryStore."""
    store = RecordStore(tmp_path / "state_isolation.db")
    store.init_schema()
    tracer = Tracer(tmp_path / "isolation_trace.jsonl")

    memory = MemoryStore()
    agent_alpha = _build_agent(store, tracer, memory)
    agent_beta = _build_agent(store, tracer, memory)

    Scheduler(CONTAMINATION_SCRIPT).run(
        lambda: agent_alpha.run_steps("alpha", "run-a"),
        lambda: agent_beta.run_steps("beta", "run-b"),
    )

    alpha_summary = store.get_summary("alpha")
    assert "beta" not in alpha_summary["content"].lower()
    assert "alpha" in alpha_summary["content"].lower()


def test_recovery_resumed_run_has_no_beta_data(tmp_path):
    """Crash + resume with a REUSED run/attempt id.

    1. Alpha reads and reasons, then crashes before saving.
    2. Beta runs to completion on the same attempt id ("slot-1") -- ids get
       reused by schedulers and retry queues.
    3. Alpha's work resumes and saves from its checkpoint.

    Keyed by run_id, step 3 loads Beta's checkpoint -> Alpha's summary leaks Beta.
    Keyed by the tenant, Alpha finds its own work.
    """
    store = RecordStore(tmp_path / "state_recovery.db")
    store.init_schema()
    tracer = Tracer(tmp_path / "recovery_trace.jsonl")

    memory = MemoryStore()
    agent_alpha = _build_agent(store, tracer, memory)
    agent_beta = _build_agent(store, tracer, memory)

    reused_id = "slot-1"

    # 1. Alpha crashes after reasoning, before the save step.
    alpha_run = agent_alpha.run_steps("alpha", reused_id)
    for step in alpha_run:
        if step == "reason":
            break  # process dies here -- save never happens

    # 2. Beta runs fully, reusing the same attempt id.
    agent_beta.run("beta", reused_id)

    # 3. Alpha resumes and saves from whatever its key points at.
    agent_alpha.save_from_checkpoint("alpha", reused_id)

    alpha_summary = store.get_summary("alpha")
    assert "beta" not in alpha_summary["content"].lower(), (
        "resume restored another tenant's checkpoint -- key memory by the unit of work"
    )
    assert "alpha" in alpha_summary["content"].lower()
